### ISSUE TITLE
✅ checkstyle 적용하기(자바 Lint)

### ISSUE THREAD

**Issue by Sehee-Lee-01** [backendoori/ootw-backend#11]
# Issue: ✅ checkstyle 적용하기(자바 Lint) #11

## Description
Code Style에 맞춰서 checkstyle 적용하기

## Todo
- [x] 구글 [google checkstyle](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) 적용 후 커스텀
- 기본 세팅 
  - [x] 클래스 앞 뒤 한 줄 설정
  - [x] 한 줄 너비 120 설정
  - [x] 와일드 카드 미포함 수정 
  - [x] 패키지 네임별 순서
## ETC
- ### 추후 해야할 일(참고) 
- ### 이슈 외에 추가로 한 일
  - [x] 줄바꿈은 CRLF 대신 LF로 변경
    - 이유: 윈도우는 줄바꿈 문자가 CRLF(`\r\n`), 맥과 유닉스는 `\n`라서 추후 포맷팅했을 때 발생할 수 있는 문제 미리 정의. 또한 AWS 환경에서 운영하게 된다면 리눅스 환경이기 때문에 이 설정을 하는 것이 좋겠다고 생각!
- html 리포트
- 쿼리 DSL 스타일 확인
- [메서드 라인 제한](https://checkstyle.sourceforge.io/checks/sizes/methodlength.html#MethodLength) 확인만 해보기 => 기능이있다!

**Comment by Sehee-Lee-01** [comment]
build.gradle에 설정 확인해보기

**Comment by Sehee-Lee-01** [comment]
maxWarnings = 0 설정

**Comment by Sehee-Lee-01** [comment]
tab보다는 스페이스 4개로

**Comment by Sehee-Lee-01** [comment]
html 리포트
