### ISSUE TITLE
✅ CI 적용하기

### ISSUE THREAD

**Issue by Sehee-Lee-01** [backendoori/ootw-backend#12]
# Issue: ✅ CI 적용하기 #12

## Description
- pull request 적용 시 자동으로 테스트와 lint 적용등이 가능하게 CI pipeline을 구축 필요

## Todo
- [x] CI 툴 선택(github action vs jenkins)
- [x] 선택에 따라 CI 설정
- [x] 설정 후 정상 작동하는지 확인 필요

## ETC
- ### 추후 해야할 일(참고) 
CI 설정 이후 pull reque 시 정상적으로 작동하는지 테스트 필요

**Comment by shoeone96** [comment]
github action 도입 시 초안 작성

```yaml
name: Spring Boot Gradle Test Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   # java 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
      # 프로젝트 빌드
    - name: Build with Gradle
      run: ./gradlew clean build
    # 테스트 실행
    - name: Run Tests
      run: ./gradlew test
```
