### ISSUE TITLE
✅ 인증 서비스 구현

### ISSUE THREAD

**Issue by Sehee-Lee-01** [backendoori/ootw-backend#14]
# Issue: ✅ 인증 서비스 구현 #14

## Description

OOTW 사용자의 인증, 인가 과정에서 사용할 기능이 필요
Spring Boot 애플리케이션 JWT를 라이브러리를 사용한 토큰 기반 인증 기능 구현

## Todo

- [ ] SecurityFilterChain 설정
- [ ] 토큰 객체 생성 기능
- [ ] Authentication 객체 생성 기능
- [ ] 토큰 검증 기능
- [ ] 토큰 기반 AuthenticationEntryPoint 추가
- [ ] 토큰 기반 AccessDeniedHandler 추가
- [ ] 토큰 기반 GenericFilterBean 추가
- [ ] 토큰 기반 SecurityConfigurerAdapter 추가
- [ ] 인증 API (#7 ) 개발

## ETC
- ### 추후 해야할 일

  - 토큰 기반 인증에서 로그아웃 기능을 구현하는 것은 쉽지 않다.
  - 추후 캐싱 서비스를 사용해서 블랙리스트 형식으로 우회적인 기능 개발이 필요
