### ISSUE TITLE
✅  이미지 관련 서비스 구현

### ISSUE THREAD

**Issue by Sehee-Lee-01** [backendoori/ootw-backend#16]
# Issue: ✅ 이미지 관련 서비스 구현 #16

## Description
- 이미지 저장 매체를 선정 후 spring project 내에서 이미지를 저장하고 불러올 수 있는 로직을 작성

## Todo
- [ ] 이미지 매체 선정(S3 vs Minio)
- [ ] 선정된 매체에 이미지를 저장하는 로직 작성
- [ ] 선정된 매체에 이미지 url 을 반환하는 로직 작성
       (아바타 이미지, 게시글 이미지의 url 저장을 위해)

## ETC
- ### 2023.12.20 오후 다같이 확인할 내용  

#### Minio vs S3 선택
  - `Minio`: 오픈 소스로 전혀 비용이 들지 않는다, 다만 인프라를 직접 관리하기는 해야 할 것으로 보임, 추후 S3로 확장 가능
  - `S3`: 저장 이후 관리는 편하게 가능, 요금이 발생할 수 있으나 소액으로 감당 가능할 것으로 추정

### 추후 해야할 일(참고) 
- 이 기능 완성 후 커뮤니티 기능에서 정상적으로 이미지 업로드와 반환을 위해 디폴트 값들을 수정할 필요가 있음
- 수정 후 테스트 과정도 필요

**Comment by Sehee-Lee-01** [comment]
일단 `minlO`나 다른 요금이 안나가는 서비스로 고려만 해보기

**Comment by shoeone96** [comment]
## ✅ minio로 결정
- S3와 비슷한 성질을 가지고 있지만 무료라는 성격을 자기고 있어서 선택

## 구현 방법
- minio 의존성 추가 후 docker container로 띄우기
- 이미지 서비스 인터페이스식으로 작성 후 구현하는 방식으로 만들기
- 추후 S3를 이용 시 S3 를 이용해서 구현체를 만드는 방식으로 진행 예정
