### ISSUE TITLE
✅ 사용자 인증 요청 및 user entity validation

### ISSUE THREAD

**Issue by ASak1104** [backendoori/ootw-backend#53]
## Description
Controller, Service, User enitty에서의 Email, Password, Nickname 필드 검증 기능이 필요

## Todo
- [ ] Email 검증 기능 추가
- [ ] Password 검증 기능 추가
- [ ] Nickname 검증 기능 추가
- [ ] 회원가입 시 image 데이터가 필요 없도록 수정
- [ ] GlobalControllerAdvice에서 필요한 Handler 추가
