### ISSUE TITLE
✅ 사용자 이메일 인증 기능 구현

### ISSUE THREAD

**Issue by ASak1104** [backendoori/ootw-backend#60]
## Description
사용자가 사용하는 이메일에 대한 인증 기능이 필요

## Todo
- [ ] 이메일이 인증된 사용자를 구분할 수 있다
- [ ] 이메일 인증은 최초 1회만 수행한다
- [ ] 인증 코드를 생성할 수 있다
- [ ] 생성된 인증 코드를 사용자 정보에 맞게 저장할 수 있다
- [ ] 인증 코드를 사용자 메일 주소로 발송할 수 있다
- [ ] 사용자 요청 시 인증 코드를 새로 생성하고 메일을 발송할 수 있다.
- [ ] 이메일이 인증되지 않은 사용자는 로그인이 불가능하다
- [ ] 이메일이 인증된 사용자는 로그인이 가능하다

## ETC
- 추후 TTL 설정을 통해 인증 코드가 만료되는 기능 추가 필요
- 추후 이메일이 인증되지 않은 사용자에 대해선 권한을 낮게 설정해서 로그인이 가능하도록 수정
