### ISSUE TITLE
🔩 이미지 기능 Refactoring

### ISSUE THREAD

**Issue by shoeone96** [backendoori/ootw-backend#82]
# Issue: 🔩 Refactoring
- 사용하고 있지않는 이미지에 대한 관리 필요
- 이미지 file 이름에 대한 관리 필요

## Description
- 사용하고 있지않는 이미지에 대한 관리 필요
    - 현재 수정, 삭제, 저장(저장 시 이미지만 저장되는 경우) 등 다양한 케이스에서 이미지가 삭제되거나 저장되고 있다.
    - 이 과정에서 이미지는 RDB에 직접 저장되는 정보가 아니다 보니 사용하지 않는 이미지가 버켓 안에 남이 있을 수 있다.
    - 사용하지 않는 이미지를 저장하고 있는 비용문제를 해결하기 위해 일정 주기로 확인해서 사용하지 않는 이미지에 대한 삭제가 필요하다.
    - 스케쥴링을 이용해 사용하고 있지 않는 이미지를 삭제할 필요가 있다.
- file 이름 관리 
    - 현재 로직에서는 파일에 사용된 이름 그대로 버킷에 저장하고 있는데 동일한 이름의 파일을 업로드 하는 경우 문제가 발생할 수 있다.
    - 파일 이름을 고유값으로 넣어 저장할 필요가 있다.
- 이미지 directory 분리
    - 이미지 서비스 비중이 커지다 보니 한 directory에 분리할 필요성을 느꼈다.

## Todo
- [ ] 스케쥴링을 이용해 사용하고 있지 않는 이미지를 삭제 기능
- [ ] file 이름 unique 값으로 관리 
- [ ] 이미지 directory 분리 및 테이블 생성
